package view;

import controller.CartController;
import controller.ProductController;
import controller.interfaces.ICartController;
import javax.swing.*;
import javax.swing.table.TableCellEditor;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;
import model.entity.Product;

public class Home extends javax.swing.JFrame {

    private List<Product> produtos;
    private List<Product> produtosCart;
    private int userId;
    
    public int getUserId() {
        return this.userId;
    }
    
    public Home() {
        initComponents();
    }
    
    public Home(int userId) {
        initComponents();
        this.userId = userId;
        DefaultTableModel tableModelProduct = (DefaultTableModel) jTableProduct.getModel();
        jTableProduct.setRowSorter(new TableRowSorter(tableModelProduct));
        for (int i = 0; i < 40; i++) {
            list1.add("GAME");        // TODO add your handling code here:

        }

        DefaultTableModel tableModelCart = (DefaultTableModel) jTableCart.getModel();
        jTableCart.setRowSorter(new TableRowSorter(tableModelCart));

        // Define o renderer e editor da coluna de ação
        jTableProduct.getColumnModel().getColumn(1).setCellRenderer(new ImageRenderer()); // Coluna de logo
        jTableProduct.getColumnModel().getColumn(5).setCellRenderer(new ButtonRenderer());
        jTableProduct.getColumnModel().getColumn(5).setCellEditor(new ButtonEditor(this));

        jTableCart.getColumnModel().getColumn(1).setCellRenderer(new ImageRenderer()); // Coluna de logo
        jTableCart.getColumnModel().getColumn(5).setCellRenderer(new ButtonRenderer());
        jTableCart.getColumnModel().getColumn(5).setCellEditor(new ButtonEditor(this));

        readJTable();
        readJTableCart();
    }

    public void updateProductTable() {
        readJTable(); // Recarrega a tabela
    }
    
     public void updateCartTable() {
        readJTableCart(); // Recarrega a tabela
    }

    // Renderer para exibir imagens na coluna da tabela
    private static class ImageRenderer extends JLabel implements TableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            // Caminho relativo para a pasta resources
            String imagePath = "/images/" + value;

            // Obtém o recurso de dentro de resources
            ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));

            // Ajuste a imagem para caber na célula
            Image scaledImage = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            setIcon(new ImageIcon(scaledImage));
            setHorizontalAlignment(CENTER);

            return this;
        }
    }

    private void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableProduct.getModel();
        modelo.setNumRows(0);
        ProductController pdao = new ProductController();

        produtos = pdao.GetAll();

        for (Product p : produtos) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getImagePath(),
                p.getName(),
                p.getDescription(),
                p.getPrice(),
                "Ações"
            });
        }
    }

    private void readJTableCart() {
        DefaultTableModel modelo = (DefaultTableModel) jTableCart.getModel();
        modelo.setNumRows(0);
        ICartController controller = new CartController();

        produtosCart = controller.GetAll(this.userId);

        for (Product p : produtosCart) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getImagePath(),
                p.getName(),
                p.getDescription(),
                p.getPrice(),
                "Ações"
            });
        }
    }

    // Método para obter o produto da linha
    public Product getProductAtRow(int row) {
        return produtos.get(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelBody = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        jTabbedPnlHome = new javax.swing.JTabbedPane();
        jPanelStore = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        txtFieldSearch = new javax.swing.JTextField();
        jPanelCategory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jLabel4 = new javax.swing.JLabel();
        jPanelCart = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCart = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAdminAddBtn = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton1)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STEAM VERDE");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/header.png"))); // NOI18N

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeaderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
            .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeaderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        jPanelStore.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanelStore.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanelStore.setPreferredSize(new java.awt.Dimension(1280, 720));

        jTableProduct.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Logo", "Nome", "Descrição", "Valor", "Ação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProduct.setAutoscrolls(false);
        jTableProduct.setRowHeight(100);
        jTableProduct.setShowGrid(false);
        jTableProduct.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTableProduct);

        txtFieldSearch.setToolTipText("Procure por um nome de jogo");
        txtFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldSearchActionPerformed(evt);
            }
        });
        txtFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldSearchKeyReleased(evt);
            }
        });

        jLabel2.setText("categories");

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCategoryLayout = new javax.swing.GroupLayout(jPanelCategory);
        jPanelCategory.setLayout(jPanelCategoryLayout);
        jPanelCategoryLayout.setHorizontalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCategoryLayout.setVerticalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Find a Game");

        javax.swing.GroupLayout jPanelStoreLayout = new javax.swing.GroupLayout(jPanelStore);
        jPanelStore.setLayout(jPanelStoreLayout);
        jPanelStoreLayout.setHorizontalGroup(
            jPanelStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelStoreLayout.createSequentialGroup()
                        .addGroup(jPanelStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 562, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelStoreLayout.setVerticalGroup(
            jPanelStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStoreLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
            .addComponent(jPanelCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPnlHome.addTab("Store", jPanelStore);

        jPanelCart.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanelCart.setMinimumSize(new java.awt.Dimension(1280, 720));

        jTableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Logo", "Nome", "Descrição", "Valor", "Ação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCart.setRowHeight(100);
        jScrollPane2.setViewportView(jTableCart);

        jLabel5.setText("VOCÊ ESTÁ COMPRANDO");

        jButton2.setText("BUY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCartLayout = new javax.swing.GroupLayout(jPanelCart);
        jPanelCart.setLayout(jPanelCartLayout);
        jPanelCartLayout.setHorizontalGroup(
            jPanelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCartLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1255, Short.MAX_VALUE)
                .addGap(105, 105, 105))
            .addGroup(jPanelCartLayout.createSequentialGroup()
                .addGroup(jPanelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCartLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5))
                    .addGroup(jPanelCartLayout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCartLayout.setVerticalGroup(
            jPanelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCartLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPnlHome.addTab("Cart", jPanelCart);

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPnlHome)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPnlHome)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBodyLayout.createSequentialGroup()
                    .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(651, Short.MAX_VALUE))
            .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBodyLayout.createSequentialGroup()
                    .addGap(354, 354, 354)
                    .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 626, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanelBody, java.awt.BorderLayout.CENTER);

        jMenu1.setText("ADMIN");

        jMenuItemAdminAddBtn.setText("Adicionar Produto");
        jMenuItemAdminAddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemAdminAddBtnMouseClicked(evt);
            }
        });
        jMenuItemAdminAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdminAddBtnActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAdminAddBtn);

        jMenuItem2.setText("Alterar Produto");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Remover Produto");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAdminAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdminAddBtnActionPerformed
        // TODO add your handling code here:
        ProductManager manager = new ProductManager(this);
        jLabel3.add(manager);
        manager.setVisible(true);

        manager.toFront();
        // Traz o JInternalFrame para frente
        try {
            manager.setSelected(true);// Traz o JInternalFrame para frente
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Dá o foco ao JInternalFrame

    }//GEN-LAST:event_jMenuItemAdminAddBtnActionPerformed

    private void jMenuItemAdminAddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAdminAddBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAdminAddBtnMouseClicked

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed

    }//GEN-LAST:event_list1ActionPerformed

    private void txtFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldSearchKeyReleased
        ProductController controller = new ProductController();

        DefaultTableModel modelo = (DefaultTableModel) jTableProduct.getModel();
        modelo.setNumRows(0);

        produtos = controller.GetByName(txtFieldSearch.getText());

        for (Product p : produtos) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getImagePath(),
                p.getName(),
                p.getDescription(),
                p.getPrice(),
                "Ações"
            });
        }
    }//GEN-LAST:event_txtFieldSearchKeyReleased

    private void txtFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    private static class ButtonRenderer extends JPanel implements TableCellRenderer {

        private final JButton btnCompra = new JButton("Comprar");
        private final JButton btnCarrinho = new JButton("Carrinho");

        public ButtonRenderer() {
            setLayout(new FlowLayout(FlowLayout.CENTER));
            add(btnCompra);
            add(btnCarrinho);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
            return this;
        }
    }

    private class ButtonEditor extends AbstractCellEditor implements TableCellEditor {

        private final JPanel panel = new JPanel();
        private final JButton btnCompra = new JButton("Comprar");
        private final JButton btnCarrinho = new JButton("Carrinho");

        public ButtonEditor(Home home) {
            panel.setLayout(new FlowLayout(FlowLayout.CENTER));
            panel.add(btnCompra);
            panel.add(btnCarrinho);

            // Configura os eventos de ação dos botões
            btnCompra.addActionListener((ActionEvent e) -> {
                int row = jTableProduct.getSelectedRow();
                Product produto = home.getProductAtRow(row); // Obter o produto
                JOptionPane.showMessageDialog(panel, "Comprando: " + produto.getName());
                stopCellEditing();
            });

            btnCarrinho.addActionListener((ActionEvent e) -> {
                int row = jTableProduct.getSelectedRow();
                Product produto = home.getProductAtRow(row); // Obter o produto
                ICartController controller = new CartController();
                controller.Add(home.getUserId(), produto.getId());
                home.updateCartTable();
                JOptionPane.showMessageDialog(panel, "Adicionado ao carrinho: " + produto.getName());
                stopCellEditing();
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row,
                int column) {
            return panel;
        }

        @Override
        public Object getCellEditorValue() {
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAdminAddBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelCart;
    private javax.swing.JPanel jPanelCategory;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelStore;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPnlHome;
    private javax.swing.JTable jTableCart;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTextField jTextField1;
    private java.awt.List list1;
    private javax.swing.JTextField txtFieldSearch;
    // End of variables declaration//GEN-END:variables
}
