package view;

import controller.UserController;
import controller.interfaces.IUserController;
import javax.swing.JOptionPane;

public class RegisterPage extends javax.swing.JFrame {
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonBack = new javax.swing.JButton();
        jButtonConfirm = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(3, 97, 91));
        jPanel1.setMaximumSize(new java.awt.Dimension(524, 387));
        jPanel1.setMinimumSize(new java.awt.Dimension(524, 387));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 97, 91));
        setMaximumSize(new java.awt.Dimension(525, 420));
        setMinimumSize(new java.awt.Dimension(525, 420));
        setPreferredSize(new java.awt.Dimension(525, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Novo Cadastro");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(216, 118, 92, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome de Usuário");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(208, 162, 107, 20);
        getContentPane().add(jTextFieldName);
        jTextFieldName.setBounds(180, 190, 160, 28);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMAIL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 220, 40, 20);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(180, 250, 160, 28);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 275, 37, 20);
        getContentPane().add(jPasswordField);
        jPasswordField.setBounds(180, 300, 160, 28);

        jButtonBack.setText("VOLTAR");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(30, 336, 74, 28);

        jButtonConfirm.setText("CONTINUAR");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirm);
        jButtonConfirm.setBounds(397, 336, 99, 28);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo100x100.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(212, 12, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundonovo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        backButtonClicked();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        confirmButtonClicked();
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void backButtonClicked() {
        new LoginPage().setVisible(true);
        this.dispose();
    }

    private void confirmButtonClicked() {
        String username = jTextFieldName.getText();
        String email = jTextFieldEmail.getText();
        String password = new String(jPasswordField.getPassword());

        if (isInputValid(username, email, password)) {
            try {
                IUserController controller = new UserController();
                controller.register(username, email, password);

                JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                new LoginPage().setVisible(true);
                this.dispose();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao registrar: " + ex.getMessage(), "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Atenção",
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    private boolean isInputValid(String username, String email, String password) {
        return !username.isEmpty() && !email.isEmpty() && !password.isEmpty();
    }

    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
